import json
from functools import reduce
from collections import defaultdict

import streamlit as st

"""
# Integration Dashboard

This dashboard tracks the status of TA1-TA4 integration by viewing
reports generated by TA4's [`knowledge-middleware`](https://github.com/DARPA-ASKEM/knowledge-middleware/).

Currently, the following features are shown on the dashboard:
- Scenario Overview: The name and description of the scenario.
- Integration Status: The status of `knowledge-middleware` calling an operation on a specific scenario.
- Execution Time: How long it took for `knowledge-middleware` to peform a certain operation.
- Logs: Unfiltered logs from `knowledge-middleware`

Terarium regularly uploads new reports to S3. Additionally, a
report can be manually generated by running the 'Report' action
on `knowledge-middleware`'s GitHub repo (NOTE: THIS MANUAL ACTION WILL LIKELY BE 
REMOVED SOON).

New scenarios may be added by creating adding a new directory in scenarios. For the
operations you'd like to test over that scenario, make sure you have the proper resources
available. To see which resource files need to exist for a specific operation, please
check [`tests/resources.yaml`](https://github.com/DARPA-ASKEM/knowledge-middleware/blob/main/tests/resources.yaml). 
Make sure to include a `config.yaml` inside your scenario directory which includes the fields:
- name
- description
- enabled (a bulleted list the operations you want to run for the scenario) 

"""

st.sidebar.markdown("""
Integration Dashboard
""")
    
